services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:80"
    networks:
      - final_network

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=application_db
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_pass
    volumes:
      - pgdata:/var/lib/postgres/data
    networks:
      - final_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "app_user", "-d", "application_db"]
      interval: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - final_network

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      - final_network
volumes:
  pgdata:

networks:
  final_network:
    driver: bridge